name: cli

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: cli-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        working-directory: packages/cli
        run: pnpm install
      - name: Build
        working-directory: packages/cli
        run: pnpm run build
  test:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        working-directory: packages/cli
        run: pnpm install
      - name: Test
        working-directory: packages/cli
        run: pnpm run test