name: docs

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        working-directory: packages/docs
        run: pnpm install
      - name: Build
        working-directory: packages/docs
        run: pnpm run build
