name: Gestalt

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: gestalt-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PNPM_VERSION: "7.13.5"

jobs:
  pr:
    name: Node ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        node: ['18.11.0']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm nx run-many --target=build --all --parallel=3
      - name: Test
        run: pnpm nx run-many --target=test --all --parallel=3
      - name: Lint
        run: pnpm nx run-many --target=lint --all --parallel=3
      - name: Type-check
        run: pnpm nx run-many --target=type-check --all --parallel=3
  main:
    name: Node ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    strategy:
      matrix:
        node: ['18.10.0']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm nx run-many --target=build --all --parallel=3
      - name: Test
        run: pnpm nx run-many --target=test --all --all --parallel=3
      - name: Lint
        run: pnpm nx run-many --target=lint --all --parallel=3
      - name: Type-check
        run: pnpm nx run-many --target=type-check --all --parallel=3
